"""Encoder-based inversion: load a trained encoder, encode + reconstruct images.

Example:
    python scripts/04_invert_encoder.py \
        --ckpt out/encoder_train/ckpt/enc_020000.pt \
        --image my_room.png --out out/inv_enc_room
"""
from __future__ import annotations
import argparse
from pathlib import Path

import numpy as np
import torch
from PIL import Image

from higan_dev.config import Config, resolve
from higan_dev.generator import HiGANGenerator
from higan_dev.inversion.encode import load_encoder, encode_image
from higan_dev.utils import load_image_tensor, save_image


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default="configs/default.yaml")
    ap.add_argument("--ckpt", required=True, help="path to trained encoder .pt")
    ap.add_argument("--image", help="path to image (or omit + use --self-test)")
    ap.add_argument("--self-test", action="store_true",
                    help="encode an image generated by G itself")
    ap.add_argument("--out", required=True)
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()

    cfg = Config.load(resolve(args.config))
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    G = HiGANGenerator(higan_repo=cfg.paths.higan_repo,
                       model_name=cfg.generator.model_name,
                       device=cfg.train.device)
    enc, w_avg = load_encoder(args.ckpt, device=G.device)

    if args.self_test:
        gen = torch.Generator(device=G.device).manual_seed(args.seed)
        with torch.no_grad():
            wp_true = G.sample_wp(1, generator=gen)
            target = G.synthesize(wp_true)
        save_image(G.to_uint8(target)[0], out / "target.png")
    else:
        if not args.image:
            ap.error("--image required when --self-test not set")
        target = load_image_tensor(args.image, size=cfg.generator.resolution,
                                   normalize="-1_1")
        save_image(G.to_uint8(target)[0], out / "target.png")

    res = encode_image(target, enc, G, w_avg=w_avg)
    save_image(G.to_uint8(res.image)[0], out / "recon.png")
    np.save(out / "wp.npy", res.wp.cpu().numpy())

    side = np.concatenate(
        [G.to_uint8(target)[0], G.to_uint8(res.image)[0]], axis=1
    )
    Image.fromarray(side).save(out / "side_by_side.png")

    if args.self_test:
        diff = (res.image - target).abs().mean().item()
        wp_err = (res.wp - wp_true).norm().item()
        print(f"self-test: pixel mae={diff:.4f}  |wp_pred - wp_true|={wp_err:.2f}")

    print(f"done -> {out}")


if __name__ == "__main__":
    main()
